# Genetic Ancestry

What is ancestry, and what can genetic data tell us? There are several ways that one can think about genetic ancestry. In these chapters, we will consider genetic ancestry to loosely mean the genetic relationship between you and your ancestors.

An important idea to remember throughout this chapter is *genetic similarity*. If you have ever taken a genetic test through a company like 23andMe or Ancestry.com you are most likely familiar with this concept. When you take one of these tests by sending in some of your DNA, these companies are reporting back to you how similar your DNA is compared to different populations.

The concept of different populations comes up a lot in these contexts. As with all scientific research, there are some ethical issues surrounding how researchers classify populations in genetic studies. We will get into this next.

\

## Describing Human Populations

When a researcher is working with genetic data, they will likely use some sort of population descriptor to attempt to capture complex differences in human genetics.

When you look at the results of your personal DNA test, you will likely see your ancestry broken down into smaller percentages of regions or peoples that contribute to 100% you. The way these regions are described brings with it some questions you may have never thought of before:

-   *How are regions defined? Are political borders used in every case?*

-   *What is the genetic "line" between being reported as native to one area versus another geography close by? How specific can this get?*

### Population Admixture

As our world has become so interconnected between geographies and people's from long ago to the present, many of us have DNA inherited from multiple populations. The general term for this is *population admixture*.



\
\

## Principal Component Analysis

If you have taken a class in linear algebra or machine learning, you may be familiar with the method of Principal Component Analysis (PCA). We use PCA as a dimension reduction method for correlated variables. We will be left with principal components (PC's) as weighted combinations of these variables that explain the most variation in our data. Essentially, instead of having thousands of SNPs, this method will group together the SNPs that contribute the most similarly to differences in population, effectively leaving us with less data overall.

The first few PC's explain the most variation in our data. Here is an example of what the PC's we create from this method look like:

\$\$ \begin{align}
\text{PC}_1 & = a_{11}x_1 + a_{12}x_2 \dots \\
\text{PC}_2 & = a_{12}x_1 + a_{24}x_2 \dots \\
\dots \\
\text{PC}_n & = a_{b}x_1 + a_cx_2 \dots
\end{align}

\$\$

\
\

## Confounding Variables



### Omitted Variable Bias

\

## Glossary {.unnumbered}

Terms for this chapter and beyond.

-   [*Pedigree*]{.underline}: how genealogical ancestors are related to each other, like an extensive family tree

-   [*Genealogical ancestry*]{.underline}: the identifiable ancestors in your pedigree

-   [*Genetic ancestry*]{.underline}: the paths through one's pedigree by which genetic traits have been inherited

-   [*Genetic similarity*]{.underline}: classifying genomes as similar to specific populations

    -   [*Population admixture*]{.underline}: the mating of individuals with different geographical and continental origins

-   [*Principal Component Analysis*]{.underline}:
